export interface Product {
  id: string
  name: string
  price: number
  category: string
  image: string
  colors: string[]
  sizes: string[]
  stock: Record<string, number>
  description: string
  isTrending: boolean
  isNew: boolean
  colorImages: Record<string, string>
}

export const products: Product[] = [
  {
    id: "1",
    name: "Classic Black Abaya",
    price: 42000, // $150 USD
    category: "everyday",
    image: "/classic-black-abaya-elegant-formal-wear.jpg",
    colors: ["Black", "Navy", "Charcoal"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    stock: {
      "Black-XS": 5,
      "Black-S": 8,
      "Black-M": 10,
      "Black-L": 7,
      "Black-XL": 4,
      "Black-XXL": 2,
      "Navy-XS": 6,
      "Navy-S": 9,
      "Navy-M": 12,
      "Navy-L": 5,
      "Navy-XL": 3,
      "Navy-XXL": 1,
      "Charcoal-XS": 4,
      "Charcoal-S": 7,
      "Charcoal-M": 8,
      "Charcoal-L": 6,
      "Charcoal-XL": 5,
      "Charcoal-XXL": 2,
    },
    description: "Timeless elegance in pure black. Perfect for everyday wear with impeccable tailoring.",
    isTrending: true,
    isNew: false,
    colorImages: {
      Black: "/classic-black-abaya-elegant-formal-wear.jpg",
      Navy: "/navy-abaya-elegant-formal-wear.jpg",
      Charcoal: "/charcoal-abaya-elegant-formal-wear.jpg",
    },
  },
  {
    id: "2",
    name: "Embroidered Luxury Abaya",
    price: 78400, // $280 USD
    category: "formal",
    image: "/embroidered-luxury-abaya-gold-ornate.jpg",
    colors: ["Black", "Burgundy", "Deep Purple"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    stock: {
      "Black-XS": 3,
      "Black-S": 5,
      "Black-M": 0,
      "Black-L": 4,
      "Black-XL": 2,
      "Black-XXL": 0,
      "Burgundy-XS": 4,
      "Burgundy-S": 6,
      "Burgundy-M": 8,
      "Burgundy-L": 5,
      "Burgundy-XL": 3,
      "Burgundy-XXL": 1,
      "Deep Purple-XS": 2,
      "Deep Purple-S": 4,
      "Deep Purple-M": 6,
      "Deep Purple-L": 3,
      "Deep Purple-XL": 1,
      "Deep Purple-XXL": 0,
    },
    description: "Exquisite hand-embroidered details. Ideal for special occasions and evening events.",
    isTrending: true,
    isNew: true,
    colorImages: {
      Black: "/embroidered-luxury-abaya-black.jpg",
      Burgundy: "/embroidered-luxury-abaya-burgundy.jpg",
      "Deep Purple": "/embroidered-luxury-abaya-deep-purple.jpg",
    },
  },
  {
    id: "3",
    name: "Silk Blend Premium Abaya",
    price: 89600, // $320 USD
    category: "premium",
    image: "/silk-blend-premium-abaya-luxurious.jpg",
    colors: ["Black", "Taupe", "Cream"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    stock: {
      "Black-XS": 6,
      "Black-S": 8,
      "Black-M": 10,
      "Black-L": 7,
      "Black-XL": 5,
      "Black-XXL": 3,
      "Taupe-XS": 4,
      "Taupe-S": 6,
      "Taupe-M": 8,
      "Taupe-L": 5,
      "Taupe-XL": 3,
      "Taupe-XXL": 1,
      "Cream-XS": 3,
      "Cream-S": 5,
      "Cream-M": 7,
      "Cream-L": 4,
      "Cream-XL": 2,
      "Cream-XXL": 0,
    },
    description: "Luxurious silk blend fabric for ultimate comfort. Premium quality and elegant drape.",
    isTrending: false,
    isNew: true,
    colorImages: {
      Black: "/silk-blend-premium-abaya-black.jpg",
      Taupe: "/silk-blend-premium-abaya-taupe.jpg",
      Cream: "/silk-blend-premium-abaya-cream.jpg",
    },
  },
  {
    id: "4",
    name: "Minimalist Modern Abaya",
    price: 50400, // $180 USD
    category: "casual",
    image: "/minimalist-modern-abaya-contemporary-clean.jpg",
    colors: ["Black", "Grey", "White"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    stock: {
      "Black-XS": 8,
      "Black-S": 12,
      "Black-M": 15,
      "Black-L": 10,
      "Black-XL": 6,
      "Black-XXL": 4,
      "Grey-XS": 5,
      "Grey-S": 8,
      "Grey-M": 10,
      "Grey-L": 7,
      "Grey-XL": 4,
      "Grey-XXL": 2,
      "White-XS": 2,
      "White-S": 4,
      "White-M": 6,
      "White-L": 3,
      "White-XL": 1,
      "White-XXL": 0,
    },
    description: "Contemporary design with clean lines. Perfect for modern, versatile everyday styling.",
    isTrending: true,
    isNew: false,
    colorImages: {
      Black: "/minimalist-modern-abaya-black.jpg",
      Grey: "/minimalist-modern-abaya-grey.jpg",
      White: "/minimalist-modern-abaya-white.jpg",
    },
  },
  {
    id: "5",
    name: "Layered Statement Abaya",
    price: 70000, // $250 USD
    category: "formal",
    image: "/layered-statement-abaya-bold-fashion.jpg",
    colors: ["Black", "Olive", "Maroon"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    stock: {
      "Black-XS": 4,
      "Black-S": 6,
      "Black-M": 8,
      "Black-L": 5,
      "Black-XL": 3,
      "Black-XXL": 1,
      "Olive-XS": 3,
      "Olive-S": 5,
      "Olive-M": 7,
      "Olive-L": 4,
      "Olive-XL": 2,
      "Olive-XXL": 0,
      "Maroon-XS": 5,
      "Maroon-S": 7,
      "Maroon-M": 9,
      "Maroon-L": 6,
      "Maroon-XL": 4,
      "Maroon-XXL": 2,
    },
    description: "Unique layered design for a bold look. Statement piece for confident women.",
    isTrending: false,
    isNew: false,
    colorImages: {
      Black: "/layered-statement-abaya-black.jpg",
      Olive: "/layered-statement-abaya-olive.jpg",
      Maroon: "/layered-statement-abaya-maroon.jpg",
    },
  },
  {
    id: "6",
    name: "Feather Light Abaya",
    price: 56000, // $200 USD
    category: "casual",
    image: "/feather-light-abaya-breathable-comfort.jpg",
    colors: ["Black", "Beige", "Sage Green"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    stock: {
      "Black-XS": 7,
      "Black-S": 10,
      "Black-M": 12,
      "Black-L": 8,
      "Black-XL": 5,
      "Black-XXL": 3,
      "Beige-XS": 5,
      "Beige-S": 7,
      "Beige-M": 9,
      "Beige-L": 6,
      "Beige-XL": 3,
      "Beige-XXL": 1,
      "Sage Green-XS": 4,
      "Sage Green-S": 6,
      "Sage Green-M": 8,
      "Sage Green-L": 5,
      "Sage Green-XL": 2,
      "Sage Green-XXL": 0,
    },
    description: "Ultra-lightweight and breathable. Ideal for warm weather and all-day comfort.",
    isTrending: true,
    isNew: true,
    colorImages: {
      Black: "/feather-light-abaya-black.jpg",
      Beige: "/feather-light-abaya-beige.jpg",
      "Sage Green": "/feather-light-abaya-sage-green.jpg",
    },
  },
  {
    id: "7",
    name: "Vintage Inspired Abaya",
    price: 75600, // $270 USD
    category: "premium",
    image: "/vintage-inspired-abaya-timeless-elegant.jpg",
    colors: ["Black", "Bronze", "Cognac"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    stock: {
      "Black-XS": 3,
      "Black-S": 5,
      "Black-M": 7,
      "Black-L": 4,
      "Black-XL": 2,
      "Black-XXL": 0,
      "Bronze-XS": 4,
      "Bronze-S": 6,
      "Bronze-M": 8,
      "Bronze-L": 5,
      "Bronze-XL": 3,
      "Bronze-XXL": 1,
      "Cognac-XS": 2,
      "Cognac-S": 4,
      "Cognac-M": 6,
      "Cognac-L": 3,
      "Cognac-XL": 1,
      "Cognac-XXL": 0,
    },
    description: "Timeless design inspired by vintage elegance. A piece that never goes out of style.",
    isTrending: false,
    isNew: false,
    colorImages: {
      Black: "/vintage-inspired-abaya-black.jpg",
      Bronze: "/vintage-inspired-abaya-bronze.jpg",
      Cognac: "/vintage-inspired-abaya-cognac.jpg",
    },
  },
  {
    id: "8",
    name: "Contemporary Chic Abaya",
    price: 58800, // $210 USD
    category: "everyday",
    image: "/contemporary-chic-abaya-modern-style.jpg",
    colors: ["Black", "Charcoal", "Navy"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    stock: {
      "Black-XS": 9,
      "Black-S": 12,
      "Black-M": 14,
      "Black-L": 10,
      "Black-XL": 7,
      "Black-XXL": 4,
      "Charcoal-XS": 6,
      "Charcoal-S": 9,
      "Charcoal-M": 11,
      "Charcoal-L": 8,
      "Charcoal-XL": 5,
      "Charcoal-XXL": 2,
      "Navy-XS": 5,
      "Navy-S": 8,
      "Navy-M": 10,
      "Navy-L": 7,
      "Navy-XL": 4,
      "Navy-XXL": 1,
    },
    description: "Modern sophistication meets comfort. Versatile piece for any occasion.",
    isTrending: true,
    isNew: false,
    colorImages: {
      Black: "/contemporary-chic-abaya-black.jpg",
      Charcoal: "/contemporary-chic-abaya-charcoal.jpg",
      Navy: "/contemporary-chic-abaya-navy.jpg",
    },
  },
]
